# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.BigIntegerField()),
                ('User_name', models.CharField(max_length=15)),
                ('User_Num', models.CharField(max_length=2)),
                ('User_birth', models.DateField()),
                ('User_email', models.EmailField(max_length=25)),
            ],
        ),
    ]
